FROM node:16-alpine

ENV NODE_ENV=production

RUN mkdir /auth-service
WORKDIR /auth-service

COPY package.json package-lock.json ./

RUN npm install --production

COPY . .

CMD ["npm", "run", "start:auth"]