FROM node:16-alpine

ENV NODE_ENV=production

RUN mkdir /api-service
WORKDIR /api-service

COPY package.json package-lock.json ./

RUN npm install --production

COPY . .

CMD ["npm", "run", "start:api"]